{% set name = "fasttext" %}
{% set version = "0.9.2" %}
{% set sha256 = "7ea4edcdb64bfc6faaaec193ef181bdc108ee62bb6a04e48b2e80b639a99e27e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/facebookresearch/fastText/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - fasttext supervised -h || [[ $? == 1 ]]  # -h returns 1

about:
  home: https://fasttext.cc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'fastText - Library for efficient text classification and representation learning'
  dev_url: https://github.com/facebookresearch/fastText
  doc_url: https://fasttext.cc/docs/en/support.html
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - JungeAlexander
    - kylebgorman
