{% set name = "fasttext" %}
{% set version = "0.9.2" %}
{% set sha256 = "7ea4edcdb64bfc6faaaec193ef181bdc108ee62bb6a04e48b2e80b639a99e27e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/facebookresearch/fastText/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - make
    - numpy >=1.17
    - pip
    - pybind11 >=2.2
    - python {{ python }}
    - setuptools >=0.7.0
  run:
    - numpy >=1.17
    - pybind11 >=2.2
    - python
    - setuptools >=0.7.0

test:
  commands:
    - fasttext supervised -h || [[ $? == 1 ]]  # -h returns 1
  imports:
    - fasttext

about:
  home: https://fasttext.cc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'fastText - Library for efficient text classification and representation learning'
  dev_url: https://github.com/facebookresearch/fastText
  doc_url: https://fasttext.cc/docs/en/support.html

extra:
  recipe-maintainers:
    - JungeAlexander
    - kylebgorman
