{% set name = "fasttext" %}
{% set version = "0.1.0" %}
{% set release_name = "431c9e2" %}
{% set sha256 = "58a4391c83618405c65a2319a9c2dd1b26cbb864aa4042e4496dc5297d9ac7b5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/facebookresearch/fastText/archive/{{ release_name }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - fasttext supervised -h || [[ $? == 1 ]]  # -h returns 1

about:
  home: https://fasttext.cc/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'fastText - Library for efficient text classification and representation learning'
  dev_url: https://github.com/facebookresearch/fastText
  doc_url: https://fasttext.cc/docs/en/support.html
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - JungeAlexander
