{% set name = "fasttext" %}
{% set version = "0.9.1" %}
{% set sha256 = "254ace2fc8dc3bea0fc6ad4897a221eb85c1e9adfa61d130b43398193ca1f061" %}

package:
  name: {{ name|lower }}
  version: v{{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://github.com/facebookresearch/fastText/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - fasttext supervised -h || [[ $? == 1 ]]  # -h returns 1

about:
  home: https://fasttext.cc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'fastText - Library for efficient text classification and representation learning'
  dev_url: https://github.com/facebookresearch/fastText
  doc_url: https://fasttext.cc/docs/en/support.html
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - JungeAlexander
