travis:
  secure:
    BINSTAR_TOKEN: 9BY4RmKo61vfyTMw71O0HzGghLv1wzoIXBkHsIXzvaRNaHdghe0kdIh7G/+xKXOJw05H5ojWwB0QNtTpIv4smLXwCVhvgKlHcVOHzJAL42c03En+hkrLJv3L20nOJ2aQTY8y9PI5GwJly1173ra/ygD07ILKGdfKwUQNCOjQY/kbszdTO/o9m/BFM3QmwmmLcXHD584BrPYO4X+9+2r2bvWtiSWK0bS0kY8ZdI0JIaeS/c790A8Pgt6G9H7bmUGu2jL4dVQAhFJo0l+GcXi8I2WwMMxklYBBdIa7dQa5x/y7Owydm/18zcptfXjZU4PylkqzPS/HE21s+UCNIDohNN4yiM5uNJhZrPIOxx7ay2FA1GTtvIh7NTw6QOpjNBKUowSYBAgDlopUx9zIAJK8X8Fbt9Fl0rh3smCKnA/zlhAUQpmaJk9Hm52ocEmjQy32qD9DM6/GsLf8B8KC9JoI9N57a11fNfCrGoQY884e6O8VtMkxHBrN/PJ/kPZuBVUxdQC6S20M7IqREtWa5wufAIdjdyzQ/WN2YADHjdFzv8Jf4tYRdbitPmP4T8j+TQRgzrgi/9eWR8MuIDcsokEqpCt1egEhiEx0PJ4zt9wEVbYarm0UEl8nTo9LDg00b5MY+o+8/MAmIAUghfJr66wG3Mqm8aIOxtWoJKO20DORWT4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
